//
// Created by liu on 18-12-7.
//

#include <boost/test/unit_test.hpp>
#include <4-1.h>

BOOST_AUTO_TEST_SUITE(question)

BOOST_AUTO_TEST_CASE(question4_1) {
  BOOST_CHECK_EQUAL(strrindex("ibkgadwrbalawpirwpvbqokoxzsrbfnzrnaenoowbajidzambrkwcbozooud", "zrna"), 31);
  BOOST_CHECK_EQUAL(strrindex(
      "rsovgxkhqbsvkzjriwhhtpnjnsthflqcqdrmrnjdvsowsqffiwjktwhzgktpqouonlhdyqwthwkgrqqudmqnzpyxyygdgewovwaqtrpcflejhbyksvjitjrfvnvgciufueqwpqrlmrytkoxanirpzraxmtitftafrntignpdfmsofurnynkwunqrybgwjkwgixbqevbrzkzjrtulbnnmqhasjuqjboqgyuuytutbvorsoihmmcpruoduaiiapvrtumldczigfdhcfjpylktajuvrrupwmhsvahejsmdbmzmcuqnpqahuaialbsiehtnktedvwfctrsarspmccznba",
      "zrna"), -1);
  BOOST_CHECK_EQUAL(strrindex(
      "rqmobpgxueirupmqziymoxaerhtmzjfumhkhvnbiqizewwoanztbbscempnzhprlyknowckajnzchecxmbuqewlrecjjyolkjpgrxxfjjlmnxhshcnemwiphdldhevktsffgogrmifpkniqrgfnanudwnfrlddtdbomgrhvgzrkfqbzoouyhcwsxviqnqcoisjrnbiskdwinvyzrnafjbhxjazyqfyqfdbjcxvuxwydahpwhfxgletaopjunziujkgzdesfqknhhjtghszznqhjrljqlcduuqlyrejchyfmsiovevkrqknfcczwxzevnovqiwdtygobjgfnjyfyzppnbaffywnavkmjshfpsuoggzvzpeainwnbyejycmslpuhwniqqivacsvauonsmimgixtuymxkowjkvnnnccoavkvjyqvsoktnnvlaicytcjoaifbtvwwuhvepjnhdfvuiycdqjbprsxnqnqgrhtixulbjgrlekihzzljjuycqyegvjcafahjhwmvmsudmzjmhqwasjkxqwdoundiecffbrdkousicjdylvmaurlddjlczpyhsaetvrxuzjjgdheclurkuhfugncxjfcddwfpbfmkvftsbiundrycnvrcqjxzfzwfostzlwtejvepxtupcpmlripk",
      "zrna"), 206);
  BOOST_CHECK_EQUAL(strrindex(
      "bafydqoigrewdxiugcywmmbowqhlyfsbrzronidnvwpbeqnrjxtrfhzrdhljphwjlqlbjpqnfrdapxzmzhcfsbhrtntndowlsogatwpliztfryempcwznwhsczowlauucrostachfkrhucscotlhlxhtqugpmqhzpdkitixjsszefoggclrahwzmsvzwxemszfgulpbknifzqgpyawymszhttcixsynuskpuxcezkpjcfhudlsibbvdbryorimrguqrslkokisozivducuzouffnbfsejcgmgqsxgklnkkoodxjwlsdpbiwonzlntcfyxaqgtjgkmiukcvnsuolemgvmdvpfavuvzcxjgfdyibsosyypgpbefqfkxecwqhmwdwzfnqasojijgcvrxawhxjkqpjpylpbxtpaxslzusupfdexgzdvwthzqbtyrppxxpidjbhttlzavqphicyhmyzjuowgsgneuwxiapfkxyfqtpvpfclhvfflpnssiabkxsyvalyfjnxaxfborduujkwzvalkzmxuawnuxdkyfxmnjr",
      "zrna"), -1);
  BOOST_CHECK_EQUAL(strrindex(
      "xtnzqdqnmqjityedltgnzgrnrfpcjqxyqdahilmhuyrhfvlkjnotrkjcgeohtvfguaieejmfdjuoluhapbdqncxwezmptujfegfitccegtopikmyuwlqcbdvointvnlledgxwymrppjicgpsyaaeebyajjxhthlcunncwejqgcfqydzzakqmwyumvhkfzjrjdlqdjjudxvvtnfyfpxicgdrubrhjhhhduakkxtzlotaggxzoepthhhbcencgbonsmjwetlbalytojbciwdbhqkzugmvrzrzmxkwnmonqoejcxkaytyzqyzvlminqutaegllwxvqysykvtuekjaqudeuifbcvwicgpetcrvbfmuyyrmgsatncxltfqbntfgexitihiycqsherevukwzvkfgikdbzxleujuqibbfntychmshrrpyotqlnhwqbnbzmnstuxmrsrcwmtotkqujrwcubxnivfhtfcwbqgkojlakikgaesioaocjdgvxoncwdvkwsmnwkbdlelqxxvdsbvylmjscgyffxkghsiposslhtdbsdhpgvaifalbxgklqljketupzrqwxrntxjifimxahtyhopknimbtcbxiygdcjgciradjngmcldjqairjlqiyxukrmzrnapujsvlipmnsnvapzspbjzjvyjdcqnsqrdutmrgmqxphxgowyrznibwzskrxwvkupbaxcocdddxupdsvibmujqbfozokskbjmopflafsqcwjaxlnrplhryhwbgvxcexmdgmtdvlhybogxdjihueophtoacfcitryrpaiumgjjqkaxyvivasdxwnukkdslobsinchyaqimcrazenqkshulvdhumtarstjqryljulreuwknoghgajgncpjpolpavsafocjzmessatmgtdtmccrdlmpwzfjcyujyskqegcogtzxslvwuycelegepdahxywhpicexygwbeonrxiqhazwzwvps",
      "zrna"), 646);
  BOOST_CHECK_EQUAL(strrindex(
      "mijqjtjcyxukyibnuzuitwzpineenmdxytwlqnxaxjuhjetxkjihdqgbljkkypzzhuiduzekchclmwhgtvcbzmzcyottshyirwcyjgpmeuwwpjkxwjogqqnfgvnnauzushkqabnhjeqzwrsahlldoloetxyhdmdjvrilbdmwajtrmucrxgotywqljbkruqtzhpknqotunencoabelpkbuzqufyxhhmmidvwehdomgtxgwwzhfemlmjqppqoazlvijceshnjrazmbaikovbbkkltmcmjpojjlrzjoywoectxndoxituwrx",
      "zrna"), -1);
  BOOST_CHECK_EQUAL(strrindex(
      "ibgonxoagmeqmkehxxtimechxuuilqxasfqsmxfnqzcioazyouuexhwifpzzuwdniggrplcgbumcjsgxdfvgyqnazhczdtdplxjjippvrkrqwhnppgduyqfsrdmikgtqydvlkjgydpttnxeyuithasehdjfbvbekvnmkhdaipofqtxddqufxhskqgopnmswjpunofwhycrfpuulvccqfsqquqmdxabhnsvhjanvtjiojffjlljudqmulzaaeeapeyusdfjogtoemiercsbsagsmicwhjjgnxsxgfbtwtcjphdqntstvngbgbtfkznksrgzuorbdljswsueslkexwupymxuttzanbltpaecwrrqwaduxvvmfhljhxekdvssondscbjtypjmdahyzukkqqogppjhkpfkdohzpnhhckhfckdvygbemdagjswiwgzmimipnteptvefvjcrkcxwajbjjzjptkgcraxejdiscymahgieiwkbatihjjzmtzngqsqcwmgdgbnmulbtnbcrzbirukfdnkgurpiewfdpdlxcaufsfxnnoiodyqziycucjiijtfzscpxjbgrlizrvngemwgncbbpmxawopqtljtglmvlluttojjalyrsneawzltzyshjrhmxtrbfybifgoakbmoeblkvfkqugjfczpfczrnabaaybylwnoxvubvszwskyxuxkcigkuvukcsvbdmmgeuwzglxgficokycabdtvvvfhbwohraetxaxfylzrqbvhghbjkcxbwahxyxpcegyftqeuducoewfbyeprfvcximymchcqsdiuvawevafaaakmbjutmgekgpdpakojzqaoryxosivvzbodzdgozngqfbklmcplnfnayghgnetcehsitntvexyqmldmjmubgbtzodxthfssjhgagczitkepchlsplsucrilziwz",
      "zrna"), 681);
  BOOST_CHECK_EQUAL(strrindex(
      "ogvfuydlugpmkodfbeyubdfgdsmzlewmzipbpxqtpcxzhtehmdnzvzrjoicrpyooxjvhpjsyjbomswkwhybxgflygqkrwfzfqkiuigjfyeewcvaxsmdschfplurawabztcgkhlpfvlvnzrdhmsehzdxexebqgcjjkqtslcpltfhvslubmxfqvvvzquengxejkkxieuogzyxiothrestldrjqdzgjxwxrltikomtdrrwxwvqvzvxglfjbtehbktlsccwuusokzvzsjyxfskkufulabynlewldptrnsfjtfvkludrzgavvricwupynpmqhuzprtwiybnrhmzilbpdtbqlhkcvfdgwhycekobtjatjeufzjghiavthnsfhyjgnrexspukneywfvmvgfezgrgdjgcnyruzzvikprvaquayrxkfxowppfkcbkhjhwocrkugufqiizvcuuantnclldq",
      "zrna"), -1);
  BOOST_CHECK_EQUAL(strrindex(
      "neyckmsawuixxaylugonxpxuuhezwivdshfweypfflecgmuyneddjexkqdzgmnvktsjrhthaovdkgniyafwfeodphgllkoodvlygoopjcopmruzyyawkqagmwwxgbzztqrcjmpaqclgrbbucwlguamvptrqverghprwsskdrmwqzjsmmzexuszfxrejrcxlhgvgmlwxpdjfonwpedwwxbblnlrodwzzxadlsfsxyntvlhmsvdwyxgbsmtpibsaekzyyqofpfcmyokvtawvuddpfsozrhbcfixmwdcrofqhlscgrfxyangfohodnajywqtbrjioaeuobgryvieabquipygtkzxdnysrirmywtnydmfesksvgzmmkvfttvbsklwslyssmemkiuhgfmetjgaannagpxlnoohxsymnnbwtxyfjyvetojoupnvhmzcpukjwgzhnhztgagwvdayhtmupgjfhjdbbfygokmleowcwrdxqqyxrvmuuvetgabfgcwojpowvvqgclxvozjfddscvoeyvtplgwvtpaosyijaxnvlxybypgbqbheekrnzrmyvpelvezrnanfwkwtbicmpiyrjuxpufavpvbiwxtvorvbrrrtawrznyghlesmamtlqfadletjlxbeglvxcyqyavcqagxfdrfehucukjwqebfbvitnsvcukhyaljxapvxdsjrjsxbtwovmsbqpjqvffpezxjvxzdnjnqykvnblhxqqbvaaemprwextsxzsagoqenwmswwspxzixtzzndsguwlwqbddwyocvpohscjudkcxmpdygsgyxkijinpalrhdqypsypynadvgyibsnwjfdnoszhztktxylpunkkykvgxfpotuvwuqwapwewvjtglsllwashekgp",
      "zrna"), 582);
  BOOST_CHECK_EQUAL(strrindex(
      "wculieeymdfdcalmxqoaswnnqxgnsalxmfrrfzlstyhbpofqwzygqbzjykcfppycgibwrucgpwhkuhtloqkyqxtsboczyrvmxhflzvygowpnxhjkiuwwdxepuphgqkpksiuoksdemiirgpwhnyezhopzjfnpqyvivfgvyshspzljvzrburucptgwffoxwmmgjotmmegehkvroyywkwthifnjrrfkpyowaagvqczuauuruopgwwrahztkkmufbabtkmttlmunvqecwpagfipurhspgyfjbuzawfkmocjxuvqxbmzggmyvmpofxhcvkipzrxbwkicbhlgmufsvnjommcgytcpefokliiljtsuzfhpnaqhseliemciruhidedoovpnohdfclxeflazhvepgexozqabtomrrtdrgqrhoyamrdgmavbamhztugchczjkmdepcnoeyqjdtwqebuobpkotookrltecqlpjgherhwvikmboycfctuceermasobescovmsydmnxedmddjfqpjnlquvttxilveklemqowbuoyuuzobriifgwjnfzdkbwmegfsaxgjiqtqxsluffcxshfqfgkgsanywxiuzkrkwoddqeqjqcljipmjzwztmlopskbvueymimowriltsqsfyuruwbszjutxvwtnmjfqsgwylqzbehtmglxmefptohalpcnccxrxjmygnoudqapikayayildqizygiqtjllmkadsmeilynadhkrbcpcyzcgdiejixzqpjiojztgswtfozerdowqxwaphsrjtxsxxjlenkbasfaoxzzsvmhdfynazwxjybudthzjpshuojttprabdgwu",
      "zrna"), -1);
  BOOST_CHECK_EQUAL(strrindex(
      "hpykishcgtkrjffkdxvbimexribvujttksfbnrgbwzwgfzhjydlwmjafiocqfoenwvhyopawawwihcmxfpzgehuysyxlphemmuwhmfdfjslfmovupxubxundgnatpxmkeidqrbaezwwwvfpefqqfqwyzrnanqdbsxqwtsduvviwcqxxvdnlltbzvrzlqlyfolzlzsx",
      "zrna"), 151);
  BOOST_CHECK_EQUAL(strrindex(
      "tlmsxqkrdjjofndmgqlvydoclltadpgowyjtbxiywyvstofgqvhltdxqfqbzvvifpwrhchnkjsjweppgfndradjzkbpcuflrblfginpjrdvkwvkfkubjtiipiurwnnwrfrkirvkjhffmbtbjtkldmibgxkbjrsruqubmacjnauynkrjahsefnvasduuorldxltadhpdbgevuwbluvmjxqayzcugbbqpyfyopzgossrrkkfiwphiisvsanisaszslrjaoztblfpdyrhiehyngwlzdfzxwhqatfyoglqachmzrctplscektpbebrnqeltgucowymfbmleqablzzallukchzbtxgyofsbuawkjhlzwofygxsvgcdwlbhrhmfsrqifoezjxwisfjecvibwiskklhyaeszjjtwyftmqjgkvpktwlnljb",
      "zrna"), -1);
  BOOST_CHECK_EQUAL(strrindex(
      "dsxrlsvhclqscnnuehcyqasalmgwkymsqkkohajpdvizovxrhkmskcfafzgqnkczrnbeiuqhlvwjusrpkirdchlvztndqrmcltgrcpcvnpajkmfshosoppjmfqkqspqunyembkmafbhbeaitdqbauwudekjvthhwivxomvswklteuiqgveapnrjcwbxkcmanixrmwloidsfnjpfkctciijcajwrstfnfxodgfxfakexsacysrygyconmdcieeyppflhpdhhjyydopcvjrehjdxftemaupwnafyhozqtlvvnsxsctcaxsyqqmpmdxzrnajiyupznhcvddqkqlfjtwqosjqrqrwnaqwgdudumdtyasinkfpwciaxhjrynrgzbdiqdvdvsejgdkhhstplnpfvgqnixbllfbqwbondfelighkellujdcjiuwzzdvcftjsnewjjwxternbjaiuldbtaqmswqsujrwszengmoykxuasedakirbjbjgrwccrjywvkmpjdzorgalwnudhphgvlpklynkcofnipkddswmfmvkifgltflyld",
      "zrna"), 316);
  BOOST_CHECK_EQUAL(strrindex(
      "pzjswgzmwwexqbvbnvyhkkvlmoezucerfihhykdsaqoxneavmvssvglrzsayhoimhmblzsjjnlwpabftwayjyebtncrzjsedffknznlrjbxtwgunziqwirwhimusoaxejlvgefiprxojpcnuagjsypgzbdgjipjzanbfoziduqwcslnqtaegeojeeemfadekceetdmvjcvcnevopjxiteffshtnxjdrggafwcruzoswqonjdwpqonilcjaploegubfbdufwbolvlvlohxmygscpihpafdouvwbdbjupeyyuspjyhgnqkhfubqxumwxccxzawcafghqzlyutxdexktpfczobqenvioaknghvyjiecwllzumsbqsbopyopwboyrrbihwjugdjbawudtjxyjskaadnqbdhbmooguruzhmyafswxcpftqbhipyjhxdrsfyebpazntfkiebtjkwxybevagywxghfusedaybqackjxnblnnybuocteklkdcccaovxdlwykqenafoktazhudijtuinsqqjlivvdumwwvdtkrgysgtygnbdizwbchqhhqtcefbjcxhuoarhwcbmwcpszfowalrprggjsyjxxoqtqvzdmbyaejzbahochcrxwtribkdowalgskkdxakmcapscfsjwxwdcvyopybsjbzytxgrtndgafhffkfkljuadsyxoaehxsbxpoquxxhmwhzcxnrtmblsrbqvruaqbhrrfydyhplrytzeqewgrqpxogsmu",
      "zrna"), -1);
  BOOST_CHECK_EQUAL(strrindex("tiezxnjfvniwndjnqsljacundxzntsxcqatdakfgvcyveurjgxbpirdgqozrnakujvqmzoofcpey", "zrna"),
                    58);
  BOOST_CHECK_EQUAL(strrindex(
      "uvpdxvpokvexviuvzzhabybeqdssczjiyuxlboflnllxstuweizvukllwuxihrdczmxvlqdissjsppjnpryrtgkazgrhlwulcjqnwmzeaizjkuijsbrsuitgbxysbtzpksuhxssybtotdgdnwqvkeadvmlkcqujrdxnurivqkmzjlikvvbfivjrpnjgmnsmvtwuizelcxxerbcuwvtklprjetphdzpwiwwoondgderywvdcaquwkfmacgzxrqvnfueabbcuwdjuniaifwhsilxrsvbljcetredwxxvalpnaxkmwrdvuqgpnkxcwvlivyslpiqqcwfivpfpjlzyistljiwipxshfznzbxpxlfbluqldhlcslwqsbasldakqidjjaryxfemvhpsrkvgghpwnlabphupmpuqylzlaiqyhewukrlythueinyyzwpfyxikhxyvkwzefgfwzbpdcrhdgqjogjmkvlbctybqaqqwixsdtnfsicqlzlwgdtqaysxyyhysixyecntaorcnbwhnxrtjrpaurjfxlfjkfoxkiiazjkeargoputjpbnvylwbynfydghhfjttemascuifqjn",
      "zrna"), -1);
  BOOST_CHECK_EQUAL(strrindex(
      "ywhryssejqrkaowqjbomlwoolzcxgrrihgxdwwtfwrxthbvydxxdnaxkmbvtinobtjwvuibjefnfdxtlndvvijkfpfcwccwpbkncivmprwvvxtncbpzpxhsezvahjtlgpqojllwijcpzjcuffquozrkgwmnnemlanquvglirnwobuwysxfdbpuawlbzfzyblfxryxyjvvrnjuicrklwqkzzhxiswbblwvvcergxahvniyveddtxuixwwnlhlvskotwmhrltpmbegvwiiaknzvawfuabxlshvwkslxrxwbnfezeufohrcsccgosenqjkxikrudvehibxgnnxqpvysaarxlqeuwoyscutffnluewgiewrenfadroizrnazmmhfasztklsknwladhwbfjgwseateiyzehkmhcgcmnqdxuggjrgpsvaevavaiiltrssmarnqxwtimgjzfqbxeqidhwlctmyaqsdistgggqsghngpfnuxdsjfjkdvrvswyevorlhzagnuomxnmeguimdbhptpjuszbjdvtdzuqrdqah",
      "zrna"), 375);
  BOOST_CHECK_EQUAL(strrindex(
      "reunlyrmvogtejsjqkzdtnkakfzxifqerqcplgewcpjimmrktbjybziqyzeqkhkppelrztvizybtbueyjnsynuvtdpvvaarbbzlqwnamwztjemzflgckntafgtgtxlermygmjctaaefzpuecfrvatnzdzclrhxmxemti",
      "zrna"), -1);
  BOOST_CHECK_EQUAL(strrindex(
      "vgovebyezlfavaapdqszhjqcbvqyuixmpowgqvpaliqecsfzrnaigfuczquemeniyttbqeendoftxbqcenjoqzbwvpmidnopjvoxipqauxxedtmypvrruikdqdurvqhzwvagukombgjgorswkjfqagapqrcycprgjauhooukmczagwjqnmleoceabobcczvdqlpkpbgrxejbycfgrhmdpoarlgkviosffffcydwttmdbqrtbiqyiolnhcdfazkxanfzwnyywneg",
      "zrna"), 47);
  BOOST_CHECK_EQUAL(strrindex(
      "ivwzbjwdgxlwornazxcimvpmcygvjvucrftnucisytusmyiemvfmtxutcorlomcsfixtelttergdwdfaglcpekayplctdrmpqjioctoyracuvqduwjsanarkxdcxikukypokwfapcybxrlpoecosgebdjdcvyiespexwidracasoaszwbncfllmdibryimaaeqbjvuwjypryxnxwwtoigdxngsbsmomtnnlskcjokwolwirrqoyouwycdjahdpflhfobaafvysphsqxadxdgfaupmlqgladwcbghevyqdrvlekqhjihddjslhqatbgfamedlktiqizrjqhecfjtqst",
      "zrna"), -1);
  BOOST_CHECK_EQUAL(strrindex(
      "uxbwhxzpwochzxysbxwzajkyuvzizrnambwdkucgtghexqrcxvzxyuatxqcsxejcasqvvwmnyeibcgnujevytdrygugxozzfifchgltekfnihiqipzlxmommgmlzddmzhcwhewqrjslkgncjmcvqnxrllxqiqyghtpfboxtdaqhqduyczytwdedbjjlxxnpdadgrpsnaqxcdxtqedmbggovzogvpjwmsxjtofpwtynviomjxerkspnjaxzboizxiuhcclkwuxvrfnuiscysruqvmlhinpkjdzeuk",
      "zrna"), 28);
  BOOST_CHECK_EQUAL(strrindex("wyxanndrssjxpcikoruwizwzp", "zrna"), -1);
  BOOST_CHECK_EQUAL(strrindex(
      "blynrppyigrkdeksfebuqbojojygmxorqyygccufluzrqyjefbwsohtczdejvrupamgmfwwhnefewnumgtxbhvplpqwytljfahpuxwebphqmninuamcvaevtvcqpyazzrnajzcygvodmjjodrmvrexjyhrpqdejqtmskivazpuzojamcalnwkttpnwhijewilgwrzgzqdwhjnnmuxlzkyshhegbufwjvisabquqbtjeikdkhpivukokveqczdzmqczhdcvkdyskjfwjzawshapjkswcgwlsngxmolfdvbdznzwqvtuhwbokngwczjoudwvqveitnbrpvmumfiqpvhrvepomtsnqmufvsqqhnwwpemxgdfscqhdkqrsrkshmmlmcgpcllzrpbihzjezzwksssrnswaarfzbiygnofhxrstswhgqnvpcirnyjdlevfcbqwgjrxpmbvhwqcgyefzwojtembtroosjrnpamhivgvhyntgdwhbaqqhllpdtwnvvqxqxktpvztzavirmajzdourpvubiothlquvaaxexoewidnixgbxbnfyvlwdnxmjrpekhrlocllzjmqktqiujsjieomkzvjucvbyhuvjlguznorctmnxtgbiwkiyacoaubcckhktptjpiuchbrmcscmbxbxdxljemkzdvhbtqrxexoxxxqhvfpthlbqomepgsmluyfcufrrcoaxhzvikossvqogayeqxcqemnkclbyxwhycuqoaowfrelndrhcrjzjxazqzspfyplaejairlysprjphghzjygdlnsrdvnowswultmsbmlmjysofprbbbyihvkmcxtskojbgsdiqhkubtllwlzgljapcdjiprvbeiduwxhxflvzqyjeizeuor",
      "zrna"), 127);
  BOOST_CHECK_EQUAL(strrindex("kftasmlwpvcdhzzeqaabrjvgjwrrnjohprgbhuyqfrynwkbiezksehhgjydgzxwflenggbokrbqxmmknvlel",
                              "zrna"), -1);
  BOOST_CHECK_EQUAL(strrindex(
      "wucjhvcylgqqszcjfpekbhsfcbnnoruwmjfpgbcofynboyvdlzcwmdncmwgewiafosjmcolnqwhufsygcydlicaxkkqedetzxzrfmujpynyakkaoaletkymjvyzenywjmhtqmklzmlocecbikqdkdzvbepuoyothvwldljjpkngvkboiligyrzyejanclxipwtzwoghnhagxxduvjxoggwqthzcdjflnieinfkzyoutvxanxvvamreaxylourbfsrrvdushpaxtmnxubibmlbacdwarvghvshetccvpkbufgxgehyktqvejlakjzgajznacwdjiqpcjamohhznqvnwjbsolrvawihdftedesrrondtdqmpisbmcrwdeujeqfiwjxgtpcyzclpyqsqyoipktzsvacmsxbnycdvrzpppzswwkziicemlkygqgsgepuuuswgxjbedteknpmrraxrlcxpmbtavuftdpajpkqrugyurfclflrrsnkesqxmutkyegunuznrjmwtfajhwoeakulssibkxrfgdemmevryghwajaekrtcmovjqdehsnwigwmueloapfaknaieibxahjvkzjyeemjddbmeyfvhxfvjusamfojmsjpsklwhtnnsavmlsevgwrqphhelqcltzjyicbenhsskihqyrzrnahbjfofukrncvddczyrfiegosjulnkbxnrpifgjalanxamhtokqwyakwpnroynvrkbgpsetwoathzrxyomgzzajzfuokaneipldrotxlerisntowosffvgqntuwdejctypsilbxqfknmcjdxdppoxhvqhyuihsoqtrdvbykeueqwhzhswatzhfezlchnzrduakyvahgtdgeehpvxctqgreefhbqlcouqqgveceaitlpfvaopyxhkaoygnlfulwgedutqr",
      "zrna"), 677);
  BOOST_CHECK_EQUAL(strrindex(
      "yqjojejfayjwszzicanrogdteqqpgvicktpkcciwxvogrngwoewhgomitdsayvchhunpxuyvbsajkangbgwbojejsxiqndsmhhiabxvmvaxdcxzvcwdfljbqkrtlyysgyeykpxbtifhkmgkqhyctaaskjpgnjxoeducmdvehyrqldqobqfhixoulvdpsouiwrfdsswibczabzukualrwvcjmwoouyzdrzumrtdglsktsrsndsorpbeovshsjfclpmxtlatwzzidrpmndgseannliexrjbopbgryfpijljjyomfvsgdfdulhjwjgyggbgxkxaeqhwhxqtrhyfbovgfzxewiebewunlkmkoxtqdoisfnncjtjvqywscffrwxyuiolsvqvoylohhjkzrneptreuaaoqwuvcdxdrvwdatiedyxecdedgchxmagnlhxljghioidrmfbpfmoyiysxlrakbqekoksincusqkmezhvonrmllwzdpjlybbmmrquogjxylzogprhqkmobypfqszytuqqohgderemfbuazreyucbboyhozwfchprvawgxjjfetqcahdfgaxdtupauihvjbhrmxilbztbplfzoobkvfcqrphyfmvmafabeceuxbzxwekfhjfyjbgyeoliwgqsplgdywjwktxcwvyilaohjorqapravlrwwecubacyuejswkfdcrajkdhxxxargtpndorupykkbiyremwfjoxxvgtnhiplxgytlkbihtqqfiujomvzwpmhxiwlckfzxxxuftvr",
      "zrna"), -1);
  BOOST_CHECK_EQUAL(strrindex(
      "nwgwxgbjmpztozfxnszbzfswnznttnpvvfbldueyvcjkxapqfwoaiestljksxqhwhkecabukazysonjozpkhrzhhbsuefhsxdkuegbiaxtrjgtzigebdarkueznmjgfxsgkvpsfikkwrpqbvlufauonkbskszubndqwmmutgocyvgzbwcqslnpzifynejtlayjyylgqrtvrfgmqezhgonlcqtdwaekdjcpcsyyuwwgcauszwiyvmuyvmawggzbmufkivblbdnutlwojsbrxtelqgnqzpzsijjsqxgezvhzrnamvscwovjmjpfeqqilikowultgphcmcofatksdnvwdldricsezitznpjfyfxkrjialvhm",
      "zrna"), 297);
  BOOST_CHECK_EQUAL(strrindex("mcnyxvgtmtmopgdajhvrtfguzknsaknd", "zrna"), -1);
  BOOST_CHECK_EQUAL(strrindex(
      "hfclxbaudrvcytwwxcdiuhfjwdyrzpwlmewfldqncclexvzxgjcyfuggzsogfnxonjvkpkptnrtcarjmyzypwwpxbeqonczvlhmmzuygdvlupcvdqfczknltvmofydieadsifilectwjaybvivaghbfeakmnhfsnqadckvreeozxvgbhyqzljegttwxwujluuxthkeqrzdgcjkgblbrpmtebmakitxnjcuoyfzpoypdzsdgxtdunovostimeiwfkdigzwiezhajhljxseunrwknfefbmrjwcrrhzrnaumsaailxrcfnvstwvasvgzjdvjugdsykiqovsrwcppidvhbbawh",
      "zrna"), 291);
  BOOST_CHECK_EQUAL(strrindex(
      "psrwqhonibeowyqqnrzphdjtvusdpbujkgzyrhutivrzkmoszncrclwapijjfgpktxpiknwmwcbdqnnnyiohprptqojtveggynhlldgigzwmttmtbocllysuwaworfpxeemxihjeukhctijqskztrdhkujlpxgolvwlvtqnertaqsojhdzajtagzwiodeiqpaokfjwwtrsoqjmcggjtoxholumkhtgmxkdwftounwzzvfknsprqwzzrwwheuatsatqwdcigqsxbfydgeahxnlycvjhjhwwylunujdwveyxoozorbmfhapmjwmehudeaybzjcalhisvtntkfdgykbjhufcsrrnhmf",
      "zrna"), -1);
}

BOOST_AUTO_TEST_SUITE_END()